apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: dummy-name-to-be-overridden
spec:
  template:
    helmRelease:
      chart:
        version: 0.31.0
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      options:
        - '30'
        - '45'
        - '60'
        - '120'
      defaultValue: '45'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      options:
        - v1.35.0
        - v1.34.3
        - v1.33.7
        - v1.32.11
      defaultValue: v1.34.3
