apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: dummy-name-to-be-overridden
spec:
  template:
    helmRelease:
      chart:
        version: 0.30.4
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      options:
        - '30'
        - '45'
        - '60'
        - '120'
      defaultValue: '45'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      options:
      defaultValue: ""
